# Generated by Django 2.2.11 on 2021-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0011_auto_20201117_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='user',
            field=models.IntegerField(db_column='user_id', null=True),
        ),
    ]
