# Generated by Django 3.2.19 on 2023-07-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0013_apirequestlog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='user',
            field=models.IntegerField(db_column='user_id', null=True),
        ),
    ]
